twig:
    default_path: '%kernel.project_dir%/templates'

    form_themes: ['form/bootstrap_4_withNoErrors.twig']
    globals:
        storeSettings: '@App\Services\StoreSettings'
        checkoutSettings: '@App\Services\CheckoutSettings'