twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    form_themes: ['form/bootstrap_4_withNoErrors.twig']

    globals:
        storeSettings: '@App\Services\StoreSettings'
        checkoutSettings: '@App\Services\CheckoutSettings'

#    form_themes: ['bootstrap_4_layout.html.twig']