index:
    path: /
    controller: App\Controller\Shop\ShopController::index

logout:
    path: /logout

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

api_login_check:
    path: /admin/api/login

# config/routes.yaml
