index:
    path: /
    controller: App\Controller\Shop\ShopController::index

admin:
    path: /admin
    controller: App\Controller\Admin\AdminController::showAdmin

logout:
    path: /logout

#admin-logout:
#    path: "/{all}/admin/logout"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

api_login_check:
    path: /admin/api/login

# config/routes.yaml
